#!/bin/bash
cd `dirname $0`
svn up .

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$1
}
fi

if ! test -e ../Boost
then {
    svn co svn://svn.felspar.com/external/Boost ../Boost
    cd ../Boost
    ./build
    cd ../fost
}
fi

rm -rf ../dist
if ./compile $VARIANTS
then {
    export LD_LIBRARY_PATH=../dist/lib
    if ../dist/bin/fost-core-test-file-io fost-core-test-file-io.txt && \
            ../dist/bin/fost-schema-test-jsondb-file Cpp/fost-schema-test/jsondb-file.json
    then {
        valgrind --leak-check=full --show-reachable=yes \
            ../dist/bin/ftest -b false \
                libfost-jsondb.so \
                libfost-cache-test-smoke.so \
                libfost-core-test-smoke.so \
                libfost-crypto-test-smoke.so \
                libfost-inet-test-smoke.so \
                libfost-schema-test-smoke.so
        valgrind --leak-check=full --show-reachable=yes \
            ../dist/bin/fost-core-test-file-io \
                fost-core-test-file-io.txt
        valgrind --leak-check=full --show-reachable=yes \
            ../dist/bin/fost-schema-test-jsondb-file \
                Cpp/fost-schema-test/jsondb-file.json
    } else {
        exit 1
    }
    fi
} else {
    exit 1
}
fi
