#!/bin/bash
cd `dirname $0`
svn up .

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$1
}
fi

if ! test -e ../Boost
then {
    svn co http://svn.felspar.com/external/Boost ../Boost
    cd ../Boost
    ./build
    cd ../fost
}
fi

rm -rf ../dist
if ./compile $VARIANTS
then {
    export LD_LIBRARY_PATH=../dist/lib
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
# You can install valgrind from http://valgrind.org/downloads/repository.html
    if ../dist/bin/fost-core-test-file-io fost-core-test-file-io.txt
    then {
        valgrind --leak-check=full --show-reachable=yes \
            ../dist/bin/ftest -b false \
                libfost-core-test-smoke.so \
                libfost-crypto-test-smoke.so \
                libfost-inet-test-smoke.so
        valgrind --leak-check=full --show-reachable=yes \
            ../dist/bin/fost-core-test-file-io \
                fost-core-test-file-io.txt
    } else {
        exit 1
    }
    fi
} else {
    exit 1
}
fi
