#!/bin/bash
cd `dirname $0`
svn up .

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$1
}
fi

if ! test -e ../Boost
then {
    svn co http://svn.felspar.com/external/Boost ../Boost
    if ! test -e ../Boost
    then {
        echo Failed to fetch Boost
        exit 1
    } else {
        cd ../Boost
        ./build
        cd ../fost-base
    }
    fi
}
fi

if test -e /proc/
then {
    DLL=so
    VALGRIND_OPTS=
}
else {
    DLL=dylib
    VALGRIND_OPTS=--auto-run-dsymutil=yes
}
fi

if ./compile fost tests $VARIANTS
then {
    export LD_LIBRARY_PATH=../dist/lib
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
# You can install valgrind from http://valgrind.org/downloads/repository.html
    valgrind --leak-check=full --show-reachable=yes \
        $VALGRIND_OPTS \
        ../dist/bin/ftest -b false \
            libfost-core-test-smoke.$DLL \
            libfost-crypto-test-smoke.$DLL \
            libfost-datetime-test-smoke.$DLL
    #valgrind --leak-check=full --show-reachable=yes \
    #    ../dist/bin/fost-core-test-file-io \
    #        fost-core-test-file-io.txt
} else {
    exit 1
}
fi
