FROM kayess/fost-updated:trusty
MAINTAINER Kirit Saelensminde

RUN \
    apt-get install -y libboost-system1.54.1 libboost-filesystem1.54.1 \
        libboost-regex1.54.1 libboost-thread1.54.1 libboost-date-time1.54.1 && \
    apt-get clean
