FROM kayess/fost-updated:precise
MAINTAINER Kirit Saelensminde

RUN \
    apt-get install -y libboost-system1.46.1 libboost-filesystem1.46.1 \
        libboost-regex1.46.1 libboost-thread1.46.1 libboost-date-time1.46.1 && \
    apt-get clean
