#!/usr/bin/env bash
cd $(dirname $0)

set -ex

# Ensure IP forwarding is enabled
sudo sysctl net.ipv4.ip_forward=1
# Set up port forwarding for 3242 to apt-cacher
IPRULE="PREROUTING -t nat -p tcp --dport 3142 -j DNAT --to-destination $(host apt-cacher | grep -o "[0-9]*.[0-9]*.[0-9]*.[0-9]*$"):3142"
sudo iptables -C $IPRULE || sudo iptables -A $IPRULE

# Make sure we have the latest source image
sudo docker pull racker/precise-with-updates

for BUILD in builder; do
    sudo docker build -t kayess/fost-$BUILD $BUILD
    sudo docker push kayess/fost-$BUILD
done
