FROM kayess/minit-restart:latest
MAINTAINER Kirit Saelensminde

RUN \
    apt-get install -y libboost-system1.55.0 libboost-filesystem1.55.0 \
        libboost-regex1.55.0 libboost-thread1.55.0 libboost-date-time1.55.0 && \
    apt-get clean
