FROM kayess/minit-restart:trusty
MAINTAINER Kirit Saelensminde

RUN \
    apt-get install -y libboost-system1.54.0 libboost-filesystem1.54.0 \
        libboost-regex1.54.0 libboost-thread1.54.0 libboost-date-time1.54.0 && \
    apt-get clean
